# Numpy

In [1]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])      # rank 1 array
print(a)
print(a.shape)
print(type(a))

[1 2 3 4 5]
(5,)
<class 'numpy.ndarray'>


In [5]:
print(a[0], a[2])

1 3


In [6]:
a[0] = 11
print(a)

[11  2  3  4  5]


In [9]:
b = np.array([
    [1,2,3,4,5],
    [6,7,8,9,10]
])
print(b, b.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]] (2, 5)


In [10]:
print(b[0,0])

1


In [11]:
print(b[0,1])

2


In [12]:
t1 = np.zeros((5,5))
print(t1)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
t2 = np.ones((2,5))
print(t2)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [15]:
t3 =np.full((5,5), 9)
t3

array([[9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9],
       [9, 9, 9, 9, 9]])

In [16]:
t4 = np.eye(10)
t4

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [17]:
t5 = np.random.random((5,5))
t5

array([[0.99013611, 0.07478448, 0.7314226 , 0.85537011, 0.3081535 ],
       [0.64770119, 0.08945768, 0.49391057, 0.04303482, 0.54732316],
       [0.98966718, 0.83478947, 0.37897528, 0.9549249 , 0.91879201],
       [0.10978994, 0.19506739, 0.40412034, 0.00717607, 0.27344208],
       [0.2217852 , 0.13061246, 0.54795022, 0.67299453, 0.83402931]])

In [18]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
b = a[:2, 1:3]         # sub array
print(b)

[[2 3]
 [6 7]]


In [19]:
print(a[0,1])

2


In [20]:
b[0,0] = 99
print(b)

[[99  3]
 [ 6  7]]


In [21]:
print(a)

[[ 1 99  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [26]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
r1 = a[1, :]
print(r1, r1.shape)

[5 6 7 8] (4,)


In [25]:
r2 = a[1:2, :]
print(r2, r2.shape)

[[5 6 7 8]] (1, 4)


In [27]:
c1 = a[:, 1]
print(c1)

[ 2  6 10]


In [28]:
c2 = a[:, 1:2]
print(c2)

[[ 2]
 [ 6]
 [10]]


In [32]:
a = np.array([
    [1,2],
    [3,4],
    [5,6]
])

print(a[[0,1,2],[0,1,0]])
print( np.array([a[0,0], a[1,1], a[2,0]]) )

[1 4 5]
[1 4 5]


In [33]:
a = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
b = np.array([0,2,0,1])
c = np.arange(4)
print(c)

[0 1 2 3]


In [36]:
print(a[[0,2,0,1],[0,1,2,3]])
print(a[b,c])

[ 1 10  3  8]
[ 1 10  3  8]


In [37]:
a[b,c] += 10
print(a)

[[11  2 13  4]
 [ 5  6  7 18]
 [ 9 20 11 12]]


In [38]:
a = np.array([
    [1,2],
    [3,4],
    [5,6]
])

b = a > 2 
print(b)

[[False False]
 [ True  True]
 [ True  True]]


In [39]:
print(a[b])

[3 4 5 6]


In [40]:
print(a[a>2])

[3 4 5 6]
